"name": "Scoring"
"main": "net.ender.cc.scoring.Scoring"
"version": "1.0"
"api-version": "1.16"

"authors": [
  #main development
    "Ender",

  #cleanup / reformatting
    "iMoltres"
]

"softdepend":
  - "PlaceholderAPI"
  - "Spicord"

"commands":
  "score":
  "team":
  "teamscore":